services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: osa_db
      MYSQL_USER: osa_user
      MYSQL_PASSWORD: osa_pass
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend:ro
      - ./data:/data
      - ./.env:/app/.env:ro
    depends_on:
      db:
        condition: service_healthy

  web:
    image: nginx:alpine
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - api
