version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: osa_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: osa_db
      MYSQL_USER: osa_user
      MYSQL_PASSWORD: osa_pass
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: osa_api
    env_file:
      - ./.env
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: osa_user
      DB_PASSWORD: osa_pass
      DB_NAME: osa_db
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
      - ./.env:/app/.env:ro
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  web:
    build:
      context: ./frontend
    container_name: osa_web
    ports:
      - "5173:80"
    depends_on:
      - api
    restart: unless-stopped
